// frontend/src/components/PorsentageChart.jsx
'use client';
import React, { useEffect, useState } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Bar } from 'react-chartjs-2';
import { getEndpoint } from '@/services/intelligence';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

export const options = {
  responsive: true,
  plugins: {
    legend: {
      position: 'top' ,
    },
    title: {
      display: true,
      text: 'Promedio de atencion vs Especialidad',
      font:{
        size:20
    }
    },
  },
  scales: {
    y: {
      ticks: {
        stepSize: 1
      },
      title:{
        display:true,
        text:"Tiempo en minuto",
        color:"",
        font:{
            size:15
        }
    },
    }
  }
};

export function PorsentageChart() {
  const [labels, setLabels] = useState([]);
  const [dataValues, setDataValues] = useState([]);
  const [backgroundColors, setBackgroundColors] = useState([]);

  const [labelsM, setLabelsM] = useState([]);
  const [dataValuesM, setDataValuesM] = useState([]);
  const [backgroundColorsM, setBackgroundColorsM] = useState([]);

  const [labelsF, setLabelsF] = useState([]);
  const [dataValuesF, setDataValuesF] = useState([]);
  const [backgroundColorsF, setBackgroundColorsF] = useState([]);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch(`${getEndpoint()}/promedioAtencion`, {
          method: 'GET',
          headers: {
            "ngrok-skip-browser-warning": "69420",
          }
        });
        const dataResponse = await response.json();
        const newLabels = dataResponse.map(item => item.especialidad);
        const newDataValues = dataResponse.map(item => item.promedio_tiempo_atencion);
        const newBackgroundColors = newDataValues.map(() => getRandomColor());
        setLabels(newLabels);
        setDataValues(newDataValues);
        setBackgroundColors(newBackgroundColors);
      } catch (error) {
        console.error(error);
      }
    }

    fetchData();
  }, []);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch(`${getEndpoint()}/promedioAtencionM`, {
          method: 'GET',
          headers: {
            "ngrok-skip-browser-warning": "69420",
          }
        });
        const dataResponse = await response.json();
        const newLabels = dataResponse.map(item => item.especialidad);
        const newDataValues = dataResponse.map(item => item.promedio_tiempo_atencion);
        const newBackgroundColors = newDataValues.map(() => getRandomColor());
        setLabelsM(newLabels);
        setDataValuesM(newDataValues);
        setBackgroundColorsM(newBackgroundColors);
      } catch (error) {
        console.error(error);
      }
    }
    fetchData();
  }, []);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch(`${getEndpoint()}/promedioAtencionF`, {
          method: 'GET',
          headers: {
            "ngrok-skip-browser-warning": "69420",
          }
        });
        const dataResponse = await response.json();
        const newLabels = dataResponse.map(item => item.especialidad);
        const newDataValues = dataResponse.map(item => item.promedio_tiempo_atencion);
        const newBackgroundColors = newDataValues.map(() => getRandomColor());
        setLabelsF(newLabels);
        setDataValuesF(newDataValues);
        setBackgroundColorsF(newBackgroundColors);
      } catch (error) {
        console.error(error);
      }
    }
    fetchData();
  }, []);

  const data = {
    labels,
    datasets: [
      {
        label: 'Tiempo Promedio de Atención (minutos)',
        data: dataValues,
        backgroundColor: backgroundColors,
      },
      {
        label: 'Tiempo Promedio de Atención Paciente Hombre (minutos)',
        data: dataValuesM,
        backgroundColor: backgroundColorsM,
      },
      {
        label: 'Tiempo Promedio de Atención Paciente Mujer (minutos)',
        data: dataValuesF,
        backgroundColor: backgroundColorsF,
      },
    ],
  };

  return <Bar options={options} data={data} />;
}

// Función para generar un color hexadecimal aleatorio
function getRandomColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

// frontend/src/app/components/porsentage-chart.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { Chart, BarController, BarElement, CategoryScale, LinearScale, Title, Tooltip, Legend, ChartOptions, ChartDataset } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';
import { IntelligenceService } from '../services/intelligence.service';
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef } from '@angular/core';

Chart.register(BarController, BarElement, CategoryScale, LinearScale, Title, Tooltip, Legend);

@Component({
  selector: 'app-porsentage-chart',
  standalone: true,
  imports: [CommonModule, BaseChartDirective],
  template: `
    <div class="chart-container">
      <canvas baseChart
              [data]="chartData"
              [options]="chartOptions"
              type="bar">
      </canvas>
    </div>
  `,
  styles: [`
    .chart-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 400px;
      background-color: #f9fafc;
      border-radius: 8px;
      padding: 16px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border: 1px solid #e0e0e0;
    }
  `]
})
export class PorsentageChartComponent implements OnInit {
  chartData: { labels: string[]; datasets: ChartDataset<'bar'>[] } = {
    labels: [],
    datasets: []
  };

  chartOptions: ChartOptions = {
    responsive: true,
    plugins: {
      legend: { position: 'top' },
      title: {
        display: true,
        text: 'Promedio de Atención vs Especialidad',
        font: { size: 20 }
      }
    },
    scales: {
      y: {
        beginAtZero: true,
        ticks: { stepSize: 1 },
        title: {
          display: true,
          text: 'Tiempo en minuto',
          font: { size: 15 }
        }
      }
    }
  };

  @ViewChild(BaseChartDirective) chart!: BaseChartDirective;

  constructor(private intelligenceService: IntelligenceService, private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.fetchGeneralData();
    this.fetchMaleData();
    this.fetchFemaleData();
  }

  async fetchGeneralData() {
    try {
      (await this.intelligenceService.getPromedioAtencion()).subscribe((dataResponse) => {
        const data = JSON.parse(dataResponse);
        const labels = data.map((item: any) => item.especialidad);
        const dataValues = data.map((item: any) => item.tiempo_atencion);
        const backgroundColors = dataValues.map(() => this.getRandomColor());

        this.chartData.labels = labels;
        this.chartData.datasets.push({
          label: 'Tiempo Promedio de Atención (minutos)',
          data: dataValues,
          backgroundColor: backgroundColors,
        });

        this.chart.update();  // Refresca el gráfico
        this.cdr.detectChanges();  // Asegura la detección de cambios
      });
    } catch (error) {
      console.error('Error al obtener datos generales:', error);
    }
  }

  async fetchMaleData() {
    try {
      (await this.intelligenceService.getPromedioAtencionM()).subscribe((dataResponse) => {
        const data = JSON.parse(dataResponse);
        const dataValues = data.map((item: any) => item.tiempo_atencion);
        const backgroundColors = dataValues.map(() => this.getRandomColor());

        this.chartData.datasets.push({
          label: 'Tiempo Promedio de Atención Paciente Hombre (minutos)',
          data: dataValues,
          backgroundColor: backgroundColors,
        });

        this.chart.update();
        this.cdr.detectChanges();
      });
    } catch (error) {
      console.error('Error al obtener datos de atención de hombres:', error);
    }
  }

  async fetchFemaleData() {
    try {
      (await this.intelligenceService.getPromedioAtencionF()).subscribe((dataResponse) => {
        const data = JSON.parse(dataResponse);
        const dataValues = data.map((item: any) => item.tiempo_atencion);
        const backgroundColors = dataValues.map(() => this.getRandomColor());

        this.chartData.datasets.push({
          label: 'Tiempo Promedio de Atención Paciente Mujer (minutos)',
          data: dataValues,
          backgroundColor: backgroundColors,
        });

        this.chart.update();
        this.cdr.detectChanges();
      });
    } catch (error) {
      console.error('Error al obtener datos de atención de mujeres:', error);
    }
  }

  private getRandomColor(): string {
    const r = Math.floor(Math.random() * 256);
    const g = Math.floor(Math.random() * 256);
    const b = Math.floor(Math.random() * 256);
    return `rgba(${r}, ${g}, ${b}, 0.5)`;
  }
}
